---
apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-failure
  labels:
    type: oneshot
spec:
  template:
    metadata:
      labels:
        type: downloadjob
    spec:
      containers:
        - name: job
          image: alpine
          command:
            - ping
            - -c
            - "10"
            - googlejksdfjkdshfkajsdfhkla.com
      restartPolicy: OnFailure